name: Package and Publish VSCode Extension

on:
  release:
    types: [created]

jobs:
  publish-vscode-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16 
        
      - name: Package and Publish
        run: |
          npx vsce package
          npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
